# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3"
services:
  chroma-vector-db:
    image: intellabs/vdms:v2.8.0
    container_name: vdms-vector-db
    ports:
      - "55555:55555"